---
title: "R Notebook"
output: html_notebook
---

Quando isto acabar, fazer 

```{r, eval = F}
source('analise_semana_virtual.R')
```

# Análise de 95

```{r}
cat_95 = as.CatDynData(x=df_effort %>% filter(year_sale %in% c(1995)),
                         step="week",
                         fleet.name="Polyvalent-S",
                         coleff=4,
                         colcat=3,
                         colmbw=9,
                         unitseff="trips",
                         unitscat="kg",
                         unitsmbw="kg",
                         nmult="thou",
                         season.dates=c(as.Date("1995-01-01"),
                                        # as.Date("1995-12-24")))
                                        last_date_of_week(1995, 52)-1))
                                        
last_date_of_week(1995, 52)-1
```
```{r}
plot.CatDynData(cat_95,
                mark = T,
                offset = c(0,1,10),
                hem = 'N')

fit_95_null = 
  trialer(cat_95,
          p = 1,
          P = list(48),
          M = 1/52,
          N0.ini = 20000, #millions, as in nmult
          P.ini = list(10000), #2 elementos porque sao 2 perturbacaoes
          k.ini = 0.01,
          alpha.ini = 0.5,
          beta.ini  = 0.5,
          distr = 'lognormal',
          method = 'spg',
          itnmax = 1000000,
          disp = list(50))


# grid_search para M, N0, P.ini, alpha.ini, beta.ini, disp

gdm_log_95 = data_frame( M_i1 = character(),
                         N0_i2 = character(),
                         Pini_i3 = character(),
                        k_i4 = character(),
                        alpha_i5 = character(),
                        beta_i6 = character(),
                      disp_i7 = character(),
                        AIC = numeric())

modelos_gdm_95 = list()

for(i1 in seq(0,10,0.001)){ #M
  for(i2 in seq(10000,1000000,50000)){ #N0
    for(i3 in seq(0, 10000000, 100000)){ # P
      for(i4 in seq(0, 1, 0.0001)){ #K
        for(i5 in seq(0, 1, 0.0001)){ # alpha
          for(i6 in seq(0, 1, 0.0001)){ # beta
           for(i7 in seq(0,1000,10)){ # disp
             tryCatch({
          res = 
            trialer(cat_95,
                   p = 1,
                   M = i1,
                   N0.ini = i2, #millions, as in nmult
                   P.ini = list(i3), #2 elementos porque sao 2 perturbacaoes
                   k.ini = i4,
                   alpha.ini = i5,
                   beta.ini  = i6,
                   P = list(48),
                   distr = 'lognormal',
                   method = 'spg',
                   itnmax = 100000,
                   disp = i7)
          modelos_gdm_95[[length(modelos_gdm_95)+1]] = res
      gdm_log_95[nrow(gdm_log_95)+1,] = c(i1,i2,i3,i4,i5,i6,i7, res$fit$Model$spg$AIC)
      },
      error=function(e){
        })
        }}}}}}}
      



# fit_95_null

plot(fit_95_null$pre_fit,
     leg.pos = 'top',
     Biom.tstep = 30,
     Cat.tstep = 30,
     Biom.xpos = 1,
     Biom.ypos = 1,
     Cat.xpos = 1,
     Cat.ypos = 1,
     diagnostics.panels = TRUE)

plot(fit_95_null$pred,
     leg.pos = 'top',
     Biom.tstep = 30,
     Cat.tstep = 30,
     Biom.xpos = 1,
     Biom.ypos = 1,
     Cat.xpos = 1,
     Cat.ypos = 1,
     diagnostics.panels = TRUE)
```

```{r}
gdm_log_95 = data_frame(distr = character(),
                        methods = character())
modelos_gdm_95 = list()
for(i in distribuicoes){
  for(j in optimizadores){
    tryCatch({
      modelos_gdm_95[[length(modelos_gdm_95)+1]] = 
           trialer(cat_95,
                   p = 2,
                   M = 1/52,
                   N0.ini = 20000, #millions, as in nmult
                   P.ini = list(10000,10000), #2 elementos porque sao 2 perturbacaoes
                   k.ini = 0.01,
                   alpha.ini = 0.5,
                   beta.ini  = 0.5,
                   P = list(48, 49),
                   distr = i,
                   method = j,
                   itnmax = 100000,
                   disp = 0.33*sd(log(cat_95$Data$`Polyvalent-S`$obscat.thou))^2)
      gdm_log_95[nrow(gdm_log_95)+1,1] = i
      gdm_log_95[nrow(gdm_log_95),2] = j
      },
      error=function(e){print(paste(i,j))
        })
  }
}

resultados = lapply(modelos_gdm_95, function(x){x$fit})

CatDynSum(x=resultados,
          season=1990,
          method=gdm_log_95$methods[1:22])
```

